<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DriveWitness</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/drivewitness.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DriveWitness.Core/DriveWitness.Core.csproj" />
    <EmbeddedResource Include="Assets/drivewitness.ico" LogicalName="DriveWitness.Icon" />
    <EmbeddedResource Include="../../LICENSE" LogicalName="DriveWitness.License" />
  </ItemGroup>
</Project>
